layout_spectrum: 0.5996024189001447
typography_spectrum: 0.24251224728550133
color:
  brandColors:
    - '#FFFFFF'
    - '#010101'
    - '#ED1077'
    - '#F35B9E'
    - '#808080'
  brandStrength: 0.6836966332792315
  lightness: 0.655232291164725
  saturation: 0.2961005624057264
  rhythmicContrast: 0.2826658977160581
content_rating:
  adult: false
github: true
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
author:
  url: 'http://www.vitaonline.link'
  email: webmaster@vitaonline.link
  name: Gustavo Domínguez
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d12e5df2-7881-4bb9-97e4-720835e6fadb.png
name: Vita Online
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d9074bf3-3a03-4f67-86e0-af6715de4c41.png
title: Vita
content: []
description: Fuck the colors.
purpose:
  - type: contact
    url: 'mailto:webmaster@vitaonline.link'
    label: Contacto
  - type: external
    url: 'http://www.vitaportal.com'
    label: vitaportal.com
