typography_spectrum: 0.7160054333534756
content_rating:
  adult: false
color:
  brandColors:
    - '#FFFFFF'
    - '#010101'
    - '#ED1077'
    - '#F35B9E'
    - '#808080'
  brandStrength: 0.026122250730024263
  lightness: 0.7894677257480672
  saturation: 0.18932863549707402
  rhythmicContrast: 0.6952946431719061
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.3588460151069235
analytics:
  google: null
  facebook: null
  twitter: null
author:
  url: 'http://www.vitaonline.link'
  email: webmaster@vitaonline.link
  name: Gustavo Domínguez
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d12e5df2-7881-4bb9-97e4-720835e6fadb.png
name: Vita Online
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d9074bf3-3a03-4f67-86e0-af6715de4c41.png
title: Vita
content: []
description: Fuck the colors.
purpose:
  - type: contact
    url: 'mailto:vita@vitaonline.link'
    label: FaceTime
  - type: external
    url: 'http://www.vitaportal.com'
    label: vitaportal.com
