name: VitaOnline.link
favicon: null
layout_spectrum: 0.91903
typography_spectrum: 0.31822647899389267
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ec1d78'
    - '#000000'
    - '#95124c'
    - '#2a0515'
    - '#4f0a28'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
