name: VitaOnline.link
favicon: null
layout_spectrum: 0
typography_spectrum: 0.73713
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2b1911'
    - '#d6ba95'
    - '#c49a6c'
    - '#6e5139'
    - '#94724f'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
